name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test --no-start
    - name: Prepare release files
      run: MIX_ENV=prod mix release
    - name: Archive distribution
      run: cd _build/prod/rel && 7z a proto.7z proto
    - uses: actions/upload-artifact@v1
      with:
        name: proto
        path: _build/prod/rel/proto.7z
